// GENERATED BY NAPL from driftdetect_io.napl — edit the prompt, not this file
//! Generation-time drift detection: reading current files off disk.
//!
//! The I/O shell of the generation-drift detector. Walks the recorded module
//! map, reconstructs each attributed generated file's baseline from the
//! journal, reads the current file off disk, and reports every file that has
//! drifted — been edited or deleted — from what the prompt last generated.
//! The pure patch replay lives in `driftdetect_replay`; the report formatting
//! lives in `drift`.

use std::collections::BTreeMap;
use std::path::Path;

use drift::{DriftReason, DriftedFile, ModuleDrift};
use driftdetect_replay::reconstruct_file_content;
use schemas_journal::JournalEntry;
use schemas_map::NaplMap;

/// Classify one attributed file, returning `None` when it matches its
/// recorded hash. I/O errors surface as their display string.
fn classify_file(
    root: &Path,
    file_path: &str,
    map: &NaplMap,
    journal: &[JournalEntry],
) -> Result<Option<DriftedFile>, String> {
    let expected_hash = map.files.get(file_path).map(|record| record.hash.clone());
    let baseline = reconstruct_file_content(journal, file_path);
    let absolute = root.join(file_path);

    if !absolute.exists() {
        return Ok(Some(DriftedFile {
            file: file_path.to_string(),
            reason: DriftReason::Missing,
            expected_hash,
            actual_hash: None,
            baseline,
            current: None,
            diff: None,
        }));
    }

    let current = std::fs::read_to_string(&absolute).map_err(|e| e.to_string())?;
    let actual_hash = hash::content_hash(&current);
    if expected_hash.as_deref() == Some(actual_hash.as_str()) {
        return Ok(None);
    }

    let diff = baseline
        .as_ref()
        .map(|base| text_diff::unified_diff(base, &current));
    Ok(Some(DriftedFile {
        file: file_path.to_string(),
        reason: DriftReason::Edited,
        expected_hash,
        actual_hash: Some(actual_hash),
        baseline,
        current: Some(current),
        diff,
    }))
}

/// Detect the drifted, attributed files of `target` across every module in
/// `map`, in map order. `module_scope` narrows the walk to one module;
/// `prompt_paths` supplies each module's prompt file, defaulting to the module
/// name.
pub fn detect_gen_drift(
    root: &Path,
    target: &str,
    map: &NaplMap,
    journal: &[JournalEntry],
    module_scope: Option<&str>,
    prompt_paths: &BTreeMap<String, String>,
) -> Result<Vec<ModuleDrift>, String> {
    let mut drifts = Vec::new();

    for (_, record) in map.prompts.iter() {
        if let Some(scope) = module_scope {
            if record.module != scope {
                continue;
            }
        }
        let Some(target_record) = record.targets.get(target) else {
            continue;
        };
        if target_record.unattributed == Some(true) {
            continue;
        }

        let mut files = Vec::new();
        for file_path in &target_record.files {
            if let Some(drifted) = classify_file(root, file_path, map, journal)? {
                files.push(drifted);
            }
        }
        if files.is_empty() {
            continue;
        }

        let prompt_file = prompt_paths
            .get(&record.module)
            .cloned()
            .unwrap_or_else(|| record.module.clone());
        drifts.push(ModuleDrift {
            module: record.module.clone(),
            prompt_file,
            target: target.to_string(),
            files,
        });
    }

    Ok(drifts)
}

#[cfg(test)]
mod tests {
    use super::*;
    use schemas_journal::{JournalFile, JournalMode};
    use schemas_map::{FileRecord, PromptRecord, PromptTargetRecord};
    use schemas_ordered_map::OrderedMap;
    use std::fs;
    use std::path::PathBuf;
    use std::process;

    /// A unique temporary directory for one test, removed on drop.
    struct TmpDir {
        path: PathBuf,
    }

    impl TmpDir {
        fn new(tag: &str) -> Self {
            let mut path = std::env::temp_dir();
            path.push(format!("driftdetect_io-{}-{}", process::id(), tag));
            let _ = fs::remove_dir_all(&path);
            fs::create_dir_all(&path).unwrap();
            TmpDir { path }
        }

        fn write(&self, rel: &str, content: &str) {
            let target = self.path.join(rel);
            if let Some(parent) = target.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(target, content).unwrap();
        }
    }

    impl Drop for TmpDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.path);
        }
    }

    fn journal_entry(
        gen: i64,
        module: &str,
        path: &str,
        before: &str,
        after: &str,
    ) -> JournalEntry {
        JournalEntry {
            gen,
            timestamp: "2024-01-01T00:00:00Z".to_string(),
            module: module.to_string(),
            target: "rust".to_string(),
            prompt_hash: "ph".to_string(),
            prompt_diff: String::new(),
            mode: JournalMode::Full,
            files: vec![JournalFile {
                path: path.to_string(),
                patch: text_diff::unified_diff(before, after),
                hash_before: None,
                hash_after: hash::content_hash(after),
            }],
        }
    }

    fn target_record(files: &[&str], unattributed: Option<bool>) -> PromptTargetRecord {
        PromptTargetRecord {
            prompt_hash_at_gen: Some("ph".to_string()),
            files: files.iter().map(|f| f.to_string()).collect(),
            unattributed,
        }
    }

    fn prompt_record(module: &str, targets: &[(&str, PromptTargetRecord)]) -> PromptRecord {
        let mut map = OrderedMap::new();
        for (name, record) in targets {
            map.insert(name.to_string(), record.clone());
        }
        PromptRecord {
            module: module.to_string(),
            prompt_hash: "ph".to_string(),
            declared_targets: vec!["rust".to_string()],
            targets: map,
        }
    }

    /// A map with one prompt, one `rust` target, and recorded hashes for the
    /// contents in `files` (path, content).
    fn map_with(module: &str, files: &[(&str, &str)]) -> NaplMap {
        let paths: Vec<&str> = files.iter().map(|(p, _)| *p).collect();
        let mut prompts = OrderedMap::new();
        prompts.insert(
            format!("{module}.napl"),
            prompt_record(module, &[("rust", target_record(&paths, None))]),
        );
        let mut file_records = OrderedMap::new();
        for (path, content) in files {
            file_records.insert(
                path.to_string(),
                FileRecord {
                    target: "rust".to_string(),
                    hash: hash::content_hash(content),
                    prompts: vec![format!("{module}.napl")],
                },
            );
        }
        NaplMap {
            version: 2,
            prompts,
            files: file_records,
        }
    }

    #[test]
    fn clean_file_matching_recorded_hash_is_not_drifted() {
        let tmp = TmpDir::new("clean");
        tmp.write("src/a.rs", "generated\n");
        let map = map_with("alpha", &[("src/a.rs", "generated\n")]);

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap();
        assert!(drifts.is_empty());
    }

    #[test]
    fn edited_file_reports_diff_against_journal_baseline() {
        let tmp = TmpDir::new("edited");
        tmp.write("src/a.rs", "one\ntwo edited");
        let map = map_with("alpha", &[("src/a.rs", "one\ntwo")]);
        let journal = vec![journal_entry(1, "alpha", "src/a.rs", "", "one\ntwo")];

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &journal, None, &BTreeMap::new()).unwrap();

        assert_eq!(drifts.len(), 1);
        let module = &drifts[0];
        assert_eq!(module.module, "alpha");
        assert_eq!(module.target, "rust");
        // No prompt_paths entry: falls back to the module name.
        assert_eq!(module.prompt_file, "alpha");

        assert_eq!(module.files.len(), 1);
        let file = &module.files[0];
        assert_eq!(file.file, "src/a.rs");
        assert_eq!(file.reason, DriftReason::Edited);
        assert_eq!(file.expected_hash, Some(hash::content_hash("one\ntwo")));
        assert_eq!(
            file.actual_hash,
            Some(hash::content_hash("one\ntwo edited"))
        );
        assert_eq!(file.baseline, Some("one\ntwo".to_string()));
        assert_eq!(file.current, Some("one\ntwo edited".to_string()));
        assert_eq!(
            file.diff,
            Some(text_diff::unified_diff("one\ntwo", "one\ntwo edited"))
        );
    }

    #[test]
    fn edited_file_without_journal_history_has_no_diff_or_baseline() {
        let tmp = TmpDir::new("nobaseline");
        tmp.write("src/a.rs", "hand written\n");
        let map = map_with("alpha", &[("src/a.rs", "generated\n")]);

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap();

        let file = &drifts[0].files[0];
        assert_eq!(file.reason, DriftReason::Edited);
        assert_eq!(file.baseline, None);
        assert_eq!(file.diff, None);
        assert_eq!(file.current, Some("hand written\n".to_string()));
    }

    #[test]
    fn deleted_file_is_missing_with_baseline_but_no_current() {
        let tmp = TmpDir::new("missing");
        let map = map_with("alpha", &[("src/a.rs", "generated")]);
        let journal = vec![journal_entry(1, "alpha", "src/a.rs", "", "generated")];

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &journal, None, &BTreeMap::new()).unwrap();

        let file = &drifts[0].files[0];
        assert_eq!(file.reason, DriftReason::Missing);
        assert_eq!(file.expected_hash, Some(hash::content_hash("generated")));
        assert_eq!(file.actual_hash, None);
        assert_eq!(file.baseline, Some("generated".to_string()));
        assert_eq!(file.current, None);
        assert_eq!(file.diff, None);
    }

    #[test]
    fn file_absent_from_the_files_map_has_no_expected_hash() {
        let tmp = TmpDir::new("unrecorded");
        tmp.write("src/a.rs", "whatever\n");
        let mut map = map_with("alpha", &[("src/a.rs", "generated\n")]);
        map.files.remove("src/a.rs");

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap();

        let file = &drifts[0].files[0];
        assert_eq!(file.reason, DriftReason::Edited);
        assert_eq!(file.expected_hash, None);
    }

    #[test]
    fn unattributed_targets_are_skipped() {
        let tmp = TmpDir::new("unattributed");
        tmp.write("src/a.rs", "edited\n");
        let mut map = map_with("alpha", &[("src/a.rs", "generated\n")]);
        map.prompts.insert(
            "alpha.napl".to_string(),
            prompt_record(
                "alpha",
                &[("rust", target_record(&["src/a.rs"], Some(true)))],
            ),
        );

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap();
        assert!(drifts.is_empty());
    }

    #[test]
    fn explicitly_attributed_targets_are_walked() {
        let tmp = TmpDir::new("attributed-false");
        tmp.write("src/a.rs", "edited\n");
        let mut map = map_with("alpha", &[("src/a.rs", "generated\n")]);
        map.prompts.insert(
            "alpha.napl".to_string(),
            prompt_record(
                "alpha",
                &[("rust", target_record(&["src/a.rs"], Some(false)))],
            ),
        );

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap();
        assert_eq!(drifts.len(), 1);
    }

    #[test]
    fn records_without_the_requested_target_are_skipped() {
        let tmp = TmpDir::new("othertarget");
        tmp.write("src/a.rs", "edited\n");
        let mut map = map_with("alpha", &[("src/a.rs", "generated\n")]);
        map.prompts.insert(
            "alpha.napl".to_string(),
            prompt_record("alpha", &[("ts", target_record(&["src/a.rs"], None))]),
        );

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap();
        assert!(drifts.is_empty());
    }

    #[test]
    fn module_scope_limits_the_walk_and_prompt_paths_name_the_prompt() {
        let tmp = TmpDir::new("scope");
        tmp.write("src/a.rs", "edited a\n");
        tmp.write("src/b.rs", "edited b\n");

        let mut prompts = OrderedMap::new();
        prompts.insert(
            "alpha.napl".to_string(),
            prompt_record("alpha", &[("rust", target_record(&["src/a.rs"], None))]),
        );
        prompts.insert(
            "beta.napl".to_string(),
            prompt_record("beta", &[("rust", target_record(&["src/b.rs"], None))]),
        );
        let mut files = OrderedMap::new();
        for (path, content) in [("src/a.rs", "gen a\n"), ("src/b.rs", "gen b\n")] {
            files.insert(
                path.to_string(),
                FileRecord {
                    target: "rust".to_string(),
                    hash: hash::content_hash(content),
                    prompts: vec![],
                },
            );
        }
        let map = NaplMap {
            version: 2,
            prompts,
            files,
        };

        let mut prompt_paths = BTreeMap::new();
        prompt_paths.insert("beta".to_string(), ".napl/beta.napl".to_string());

        let all = detect_gen_drift(&tmp.path, "rust", &map, &[], None, &prompt_paths).unwrap();
        assert_eq!(
            all.iter().map(|d| d.module.as_str()).collect::<Vec<_>>(),
            vec!["alpha", "beta"]
        );
        assert_eq!(all[0].prompt_file, "alpha");
        assert_eq!(all[1].prompt_file, ".napl/beta.napl");

        let scoped =
            detect_gen_drift(&tmp.path, "rust", &map, &[], Some("beta"), &prompt_paths).unwrap();
        assert_eq!(scoped.len(), 1);
        assert_eq!(scoped[0].module, "beta");
    }

    #[test]
    fn files_are_classified_in_declared_order() {
        let tmp = TmpDir::new("order");
        tmp.write("src/z.rs", "edited z\n");
        tmp.write("src/a.rs", "edited a\n");

        let mut map = map_with("alpha", &[("src/z.rs", "gen z\n"), ("src/a.rs", "gen a\n")]);
        map.prompts.insert(
            "alpha.napl".to_string(),
            prompt_record(
                "alpha",
                &[("rust", target_record(&["src/z.rs", "src/a.rs"], None))],
            ),
        );

        let drifts =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap();
        assert_eq!(
            drifts[0]
                .files
                .iter()
                .map(|f| f.file.as_str())
                .collect::<Vec<_>>(),
            vec!["src/z.rs", "src/a.rs"]
        );
    }

    #[test]
    fn unreadable_file_propagates_the_io_error_message() {
        let tmp = TmpDir::new("ioerror");
        // A directory where a file is expected: reading it fails.
        fs::create_dir_all(tmp.path.join("src/a.rs")).unwrap();
        let map = map_with("alpha", &[("src/a.rs", "generated\n")]);

        let error =
            detect_gen_drift(&tmp.path, "rust", &map, &[], None, &BTreeMap::new()).unwrap_err();
        assert!(!error.is_empty());
    }
}
