// GENERATED BY NAPL from healing_io.napl — edit the prompt, not this file
//! Generated-file healing: detecting moves and journaling them.
//!
//! A generated file the map tracks can vanish from its recorded path because a
//! hand `mv`, or a rename in an editor, relocated it. Rather than reporting a
//! false deletion plus an unattributed new file, this shell finds the untracked
//! file carrying the moved content, rewrites the path in the map, journals a
//! `move` entry, and relocks the file at its new path when the content is
//! unchanged. The move-match decision itself is pure and lives in
//! `healing_core`.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::Path;

use driftdetect_replay::reconstruct_file_content;
use hash::content_hash;
use healing_core::{move_verdict, MoveCandidate, MoveVerdict};
use paths_core::{rel_to, NaplPaths};
use schemas_journal::{next_gen_number, JournalEntry, JournalFile, JournalMode};
use schemas_map::NaplMap;
use snapshot_io::{snapshot_contents, snapshot_hashes};

/// One file the map tracked at `old_path`, healed to `new_path` under
/// `target`. `drifted` is `true` when the content also changed.
pub struct HealedMove {
    pub old_path: String,
    pub new_path: String,
    pub target: String,
    pub drifted: bool,
}

/// Heal every tracked file the map lost to a move, mutating `map` in place and
/// appending one `move` journal entry per heal.
///
/// Returns the heals applied, empty when nothing moved. The caller persists the
/// mutated map. `now` is the timestamp source, invoked once per journaled entry.
pub fn heal_moved_files(
    root: &Path,
    paths: &NaplPaths,
    map: &mut NaplMap,
    journal: &[JournalEntry],
    now: &dyn Fn() -> String,
) -> Result<Vec<HealedMove>, String> {
    let tracked: BTreeSet<String> = map.files.keys().cloned().collect();
    let missing: Vec<String> = tracked
        .iter()
        .filter(|rel| !fsutil_io::exists(&root.join(rel)))
        .cloned()
        .collect();
    if missing.is_empty() {
        return Ok(Vec::new());
    }

    let candidates = collect_candidates(root, paths, map, &tracked)?;
    let heals = decide_heals(map, journal, &missing, &candidates)?;
    if heals.is_empty() {
        return Ok(Vec::new());
    }

    apply_heals(root, paths, map, journal, now, &heals)?;
    Ok(heals)
}

/// The untracked candidate pool of every target the map's files name, keyed by
/// target and kept in sorted-absolute-path order.
fn collect_candidates(
    root: &Path,
    paths: &NaplPaths,
    map: &NaplMap,
    tracked: &BTreeSet<String>,
) -> Result<BTreeMap<String, Vec<MoveCandidate>>, String> {
    let target_names: BTreeSet<String> = map
        .files
        .values()
        .map(|record| record.target.clone())
        .collect();

    let mut pools = BTreeMap::new();
    for target in target_names {
        let Ok(adapter) = targets::get_adapter(&target) else {
            continue;
        };
        let target_dir = paths.src_dir.join(&target);
        if !fsutil_io::exists(&target_dir) {
            continue;
        }

        let filter = snapshot_filter::make_filter(
            &adapter.attribution_exclude_dirs,
            &adapter.attribution_exclude_files,
            &adapter.attribution_exclude_root_files,
            &adapter.attribution_exclude_suffixes,
        );
        let hashes = snapshot_hashes(&target_dir, &filter)?;
        let contents = snapshot_contents(&target_dir, &filter)?;

        let mut pool = Vec::new();
        for (abs, hash) in &hashes {
            let rel = rel_to(root, Path::new(abs));
            if tracked.contains(&rel) {
                continue;
            }
            pool.push(MoveCandidate {
                path: rel,
                hash: hash.clone(),
                content: contents.get(abs).cloned().unwrap_or_default(),
            });
        }
        pools.insert(target, pool);
    }
    Ok(pools)
}

/// Ask the pure verdict about each missing file, in order, threading the set of
/// new paths earlier heals already claimed.
fn decide_heals(
    map: &NaplMap,
    journal: &[JournalEntry],
    missing: &[String],
    candidates: &BTreeMap<String, Vec<MoveCandidate>>,
) -> Result<Vec<HealedMove>, String> {
    const EMPTY_POOL: &[MoveCandidate] = &[];

    let mut claimed: BTreeSet<String> = BTreeSet::new();
    let mut heals = Vec::new();

    for old in missing {
        let Some(record) = map.files.get(old) else {
            continue;
        };
        let baseline = reconstruct_file_content(journal, old).unwrap_or_default();
        let pool = candidates
            .get(&record.target)
            .map(Vec::as_slice)
            .unwrap_or(EMPTY_POOL);

        let verdict = move_verdict(old, &record.target, &record.hash, &baseline, pool, &claimed);
        let (new_path, drifted) = match verdict {
            MoveVerdict::Ambiguous(message) => return Err(message),
            MoveVerdict::Clean(new_path) => (new_path, false),
            MoveVerdict::Drifted(new_path) => (new_path, true),
            MoveVerdict::NoMatch => continue,
        };

        claimed.insert(new_path.clone());
        heals.push(HealedMove {
            old_path: old.clone(),
            new_path,
            target: record.target.clone(),
            drifted,
        });
    }
    Ok(heals)
}

/// Rewrite the map and append one `move` journal entry per heal.
fn apply_heals(
    root: &Path,
    paths: &NaplPaths,
    map: &mut NaplMap,
    journal: &[JournalEntry],
    now: &dyn Fn() -> String,
    heals: &[HealedMove],
) -> Result<(), String> {
    let mut gen = next_gen_number(journal);

    for heal in heals {
        let record = map.files.get(&heal.old_path);
        let module = record
            .and_then(|record| record.prompts.first().cloned())
            .unwrap_or_else(|| heal.new_path.clone());
        let hash_before = record.map(|record| record.hash.clone());

        let new_abs = root.join(&heal.new_path);
        let current = fs::read_to_string(&new_abs).map_err(|e| e.to_string())?;
        let hash_after = content_hash(&current);

        rewrite_paths(map, &heal.old_path, &heal.new_path);

        if !heal.drifted {
            fsutil_io::set_mode(&new_abs, fsutil_io::READONLY_MODE).map_err(|e| e.to_string())?;
        }

        let entry = JournalEntry {
            gen,
            timestamp: now(),
            module,
            target: heal.target.clone(),
            prompt_hash: String::new(),
            prompt_diff: String::new(),
            mode: JournalMode::Move,
            files: vec![JournalFile {
                path: heal.new_path.clone(),
                patch: format!("moved {} -> {}", heal.old_path, heal.new_path),
                hash_before,
                hash_after,
            }],
        };
        state_io::append_journal_entry(&paths.journal_path, &entry)?;
        gen += 1;
    }
    Ok(())
}

/// Move the file record from `old_path` to `new_path` and repoint every prompt
/// target record that listed the old path.
fn rewrite_paths(map: &mut NaplMap, old_path: &str, new_path: &str) {
    if let Some(record) = map.files.remove(old_path) {
        map.files.insert(new_path.to_string(), record);
    }

    let prompt_keys: Vec<String> = map.prompts.keys().cloned().collect();
    for prompt_key in prompt_keys {
        let Some(prompt) = map.prompts.get_mut(&prompt_key) else {
            continue;
        };
        let target_keys: Vec<String> = prompt.targets.keys().cloned().collect();
        for target_key in target_keys {
            let Some(target) = prompt.targets.get_mut(&target_key) else {
                continue;
            };
            for file in target.files.iter_mut() {
                if file == old_path {
                    *file = new_path.to_string();
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use schemas_map::{FileRecord, PromptRecord, PromptTargetRecord};
    use schemas_ordered_map::OrderedMap;
    use std::os::unix::fs::PermissionsExt;
    use std::path::PathBuf;
    use std::process;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static COUNTER: AtomicUsize = AtomicUsize::new(0);

    /// A unique temporary project root, removed on drop.
    struct TmpRoot {
        path: PathBuf,
    }

    impl TmpRoot {
        fn new(tag: &str) -> Self {
            let mut path = std::env::temp_dir();
            let seq = COUNTER.fetch_add(1, Ordering::SeqCst);
            path.push(format!("healing_io-{}-{}-{}", process::id(), tag, seq));
            let _ = fs::remove_dir_all(&path);
            fs::create_dir_all(&path).unwrap();
            TmpRoot { path }
        }

        /// Write `content` at the project-relative `rel`.
        fn write(&self, rel: &str, content: &str) {
            let abs = self.path.join(rel);
            fsutil_io::write(&abs, content).unwrap();
            fsutil_io::set_mode(&abs, fsutil_io::WRITABLE_MODE).unwrap();
        }
    }

    impl Drop for TmpRoot {
        fn drop(&mut self) {
            // Locked files are read-only; the directories still allow removal.
            let _ = fs::remove_dir_all(&self.path);
        }
    }

    fn now() -> String {
        "2024-01-01T00:00:00Z".to_string()
    }

    fn file_record(target: &str, hash: &str, prompts: &[&str]) -> FileRecord {
        FileRecord {
            target: target.to_string(),
            hash: hash.to_string(),
            prompts: prompts.iter().map(|p| p.to_string()).collect(),
        }
    }

    /// A map with one rust file record, tracked at `rel` with `content`'s hash.
    fn map_with(rel: &str, content: &str, prompts: &[&str]) -> NaplMap {
        let mut files = OrderedMap::new();
        files.insert(
            rel.to_string(),
            file_record("rust", &content_hash(content), prompts),
        );
        NaplMap {
            version: 2,
            prompts: OrderedMap::new(),
            files,
        }
    }

    /// A prompt record naming `files` under the rust target.
    fn prompt_with(files: &[&str]) -> PromptRecord {
        let mut targets = OrderedMap::new();
        targets.insert(
            "rust".to_string(),
            PromptTargetRecord {
                prompt_hash_at_gen: None,
                files: files.iter().map(|f| f.to_string()).collect(),
                unattributed: None,
            },
        );
        PromptRecord {
            module: "m".to_string(),
            prompt_hash: "ph".to_string(),
            declared_targets: vec!["rust".to_string()],
            targets,
        }
    }

    fn journal_lines(paths: &NaplPaths) -> Vec<JournalEntry> {
        let raw = fsutil_io::read_opt(&paths.journal_path)
            .unwrap()
            .unwrap_or_default();
        let (entries, warnings) = schemas_journal::read_journal_str(&raw);
        assert!(warnings.is_empty(), "journal warnings: {warnings:?}");
        entries
    }

    #[test]
    fn nothing_missing_heals_nothing() {
        let tmp = TmpRoot::new("present");
        tmp.write(".napl/src/rust/a/src/lib.rs", "pub fn f() {}");
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/src/lib.rs", "pub fn f() {}", &["m.napl"]);

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        assert!(heals.is_empty());
        assert!(!fsutil_io::exists(&paths.journal_path));
    }

    #[test]
    fn clean_move_rewrites_map_relocks_and_journals() {
        let tmp = TmpRoot::new("clean");
        let content = "pub fn f() {}";
        tmp.write(".napl/src/rust/b/src/lib.rs", content);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/src/lib.rs", content, &["m.napl"]);
        map.prompts.insert(
            "m.napl".to_string(),
            prompt_with(&[".napl/src/rust/a/src/lib.rs"]),
        );

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        assert_eq!(heals.len(), 1);
        assert_eq!(heals[0].old_path, ".napl/src/rust/a/src/lib.rs");
        assert_eq!(heals[0].new_path, ".napl/src/rust/b/src/lib.rs");
        assert_eq!(heals[0].target, "rust");
        assert!(!heals[0].drifted);

        // The map now tracks the new path, and the prompt points at it.
        assert!(map.files.get(".napl/src/rust/a/src/lib.rs").is_none());
        let moved = map.files.get(".napl/src/rust/b/src/lib.rs").unwrap();
        assert_eq!(moved.hash, content_hash(content));
        assert_eq!(
            map.prompts
                .get("m.napl")
                .unwrap()
                .targets
                .get("rust")
                .unwrap()
                .files,
            vec![".napl/src/rust/b/src/lib.rs".to_string()]
        );

        // A clean relocation is relocked at its new path.
        let mode = fs::metadata(tmp.path.join(".napl/src/rust/b/src/lib.rs"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, fsutil_io::READONLY_MODE);

        let entries = journal_lines(&paths);
        assert_eq!(entries.len(), 1);
        let entry = &entries[0];
        assert_eq!(entry.gen, 1);
        assert_eq!(entry.timestamp, now());
        assert_eq!(entry.module, "m.napl");
        assert_eq!(entry.target, "rust");
        assert_eq!(entry.prompt_hash, "");
        assert_eq!(entry.prompt_diff, "");
        assert_eq!(entry.mode, JournalMode::Move);
        assert_eq!(
            entry.files,
            vec![JournalFile {
                path: ".napl/src/rust/b/src/lib.rs".to_string(),
                patch: "moved .napl/src/rust/a/src/lib.rs -> .napl/src/rust/b/src/lib.rs"
                    .to_string(),
                hash_before: Some(content_hash(content)),
                hash_after: content_hash(content),
            }]
        );
    }

    #[test]
    fn drifted_move_heals_the_path_and_leaves_the_file_writable() {
        let tmp = TmpRoot::new("drifted");
        let before = "one\ntwo\nthree\nfour\n";
        let after = "one\ntwo\nthree\nFOUR CHANGED\n";
        tmp.write(".napl/src/rust/b/src/lib.rs", after);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/src/lib.rs", before, &["m.napl"]);
        let journal = vec![JournalEntry {
            gen: 7,
            timestamp: "t".to_string(),
            module: "m.napl".to_string(),
            target: "rust".to_string(),
            prompt_hash: "ph".to_string(),
            prompt_diff: String::new(),
            mode: JournalMode::Full,
            files: vec![JournalFile {
                path: ".napl/src/rust/a/src/lib.rs".to_string(),
                patch: schemas_journal::file_patch(None, before),
                hash_before: None,
                hash_after: content_hash(before),
            }],
        }];

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &journal, &now).unwrap();

        assert_eq!(heals.len(), 1);
        assert!(heals[0].drifted);
        assert_eq!(heals[0].new_path, ".napl/src/rust/b/src/lib.rs");
        assert!(map.files.get(".napl/src/rust/b/src/lib.rs").is_some());

        // A drifted move is not relocked — drift machinery reports the change.
        let mode = fs::metadata(tmp.path.join(".napl/src/rust/b/src/lib.rs"))
            .unwrap()
            .permissions()
            .mode();
        assert_eq!(mode & 0o777, fsutil_io::WRITABLE_MODE);

        let entries = journal_lines(&paths);
        assert_eq!(entries.len(), 1);
        // The gen counter continues from the journal it was handed.
        assert_eq!(entries[0].gen, 8);
        assert_eq!(entries[0].files[0].hash_after, content_hash(after));
        assert_eq!(entries[0].files[0].hash_before, Some(content_hash(before)));
    }

    #[test]
    fn no_matching_candidate_heals_nothing() {
        let tmp = TmpRoot::new("nomatch");
        tmp.write(".napl/src/rust/b/src/lib.rs", "totally\nunrelated\ntext\n");
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(
            ".napl/src/rust/a/src/lib.rs",
            "pub fn f() {}\npub fn g() {}\n",
            &["m.napl"],
        );

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        assert!(heals.is_empty());
        assert!(map.files.get(".napl/src/rust/a/src/lib.rs").is_some());
        assert!(!fsutil_io::exists(&paths.journal_path));
    }

    #[test]
    fn ambiguous_move_errors_without_touching_map_or_journal() {
        let tmp = TmpRoot::new("ambiguous");
        let content = "pub fn f() {}";
        tmp.write(".napl/src/rust/b/src/lib.rs", content);
        tmp.write(".napl/src/rust/c/src/lib.rs", content);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/src/lib.rs", content, &["m.napl"]);

        let err = match heal_moved_files(&tmp.path, &paths, &mut map, &[], &now) {
            Err(err) => err,
            Ok(_) => panic!("expected an ambiguous-move error"),
        };

        assert_eq!(
            err,
            "cannot heal moved file '.napl/src/rust/a/src/lib.rs' (rust): 2 untracked files have identical content (.napl/src/rust/b/src/lib.rs, .napl/src/rust/c/src/lib.rs). Rename or remove the duplicate so the move is unambiguous."
        );
        assert!(map.files.get(".napl/src/rust/a/src/lib.rs").is_some());
        assert!(!fsutil_io::exists(&paths.journal_path));
    }

    #[test]
    fn two_moves_claim_distinct_candidates_and_number_gens_in_order() {
        let tmp = TmpRoot::new("two");
        let one = "pub fn one() {}";
        let two = "pub fn two() {}";
        tmp.write(".napl/src/rust/z/src/one.rs", one);
        tmp.write(".napl/src/rust/z/src/two.rs", two);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/src/one.rs", one, &["one.napl"]);
        map.files.insert(
            ".napl/src/rust/a/src/two.rs".to_string(),
            file_record("rust", &content_hash(two), &["two.napl"]),
        );

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        assert_eq!(heals.len(), 2);
        // Missing files are healed in sorted order.
        assert_eq!(heals[0].old_path, ".napl/src/rust/a/src/one.rs");
        assert_eq!(heals[0].new_path, ".napl/src/rust/z/src/one.rs");
        assert_eq!(heals[1].old_path, ".napl/src/rust/a/src/two.rs");
        assert_eq!(heals[1].new_path, ".napl/src/rust/z/src/two.rs");

        let entries = journal_lines(&paths);
        assert_eq!(entries.len(), 2);
        assert_eq!(entries[0].gen, 1);
        assert_eq!(entries[1].gen, 2);
        assert_eq!(entries[0].module, "one.napl");
        assert_eq!(entries[1].module, "two.napl");
    }

    #[test]
    fn a_tracked_candidate_is_never_a_move_target() {
        let tmp = TmpRoot::new("tracked");
        let content = "pub fn f() {}";
        // The only file with this content on disk is itself tracked.
        tmp.write(".napl/src/rust/b/src/lib.rs", content);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/src/lib.rs", content, &["m.napl"]);
        map.files.insert(
            ".napl/src/rust/b/src/lib.rs".to_string(),
            file_record("rust", &content_hash(content), &["other.napl"]),
        );

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        assert!(heals.is_empty());
    }

    #[test]
    fn a_record_without_prompts_journals_the_new_path_as_its_module() {
        let tmp = TmpRoot::new("noprompt");
        let content = "pub fn f() {}";
        tmp.write(".napl/src/rust/b/src/lib.rs", content);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/src/lib.rs", content, &[]);

        heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        let entries = journal_lines(&paths);
        assert_eq!(entries[0].module, ".napl/src/rust/b/src/lib.rs");
    }

    #[test]
    fn an_unknown_target_is_skipped() {
        let tmp = TmpRoot::new("unknown");
        let content = "pub fn f() {}";
        tmp.write(".napl/src/elixir/b/src/lib.rs", content);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/elixir/a/src/lib.rs", content, &["m.napl"]);
        map.files
            .get_mut(".napl/src/elixir/a/src/lib.rs")
            .unwrap()
            .target = "elixir".to_string();

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        assert!(heals.is_empty());
    }

    #[test]
    fn an_excluded_file_is_not_a_candidate() {
        let tmp = TmpRoot::new("excluded");
        let content = "[workspace]\n";
        // `Cargo.toml` at the target root is excluded from the rust snapshot.
        tmp.write(".napl/src/rust/Cargo.toml", content);
        let paths = paths_core::resolve_paths(&tmp.path);
        let mut map = map_with(".napl/src/rust/a/Cargo.toml", content, &["m.napl"]);

        let heals = heal_moved_files(&tmp.path, &paths, &mut map, &[], &now).unwrap();

        assert!(heals.is_empty());
    }
}
