// GENERATED BY NAPL from incremental.napl — edit the prompt, not this file

use schemas_attribution::AttributionEntry;
use std::collections::BTreeSet;

const CONTEXT: usize = 3;

#[derive(Debug, Clone, PartialEq, Eq)]
enum DiffOp {
    Equal { old_line: usize, new_line: usize, text: String },
    Delete { old_line: usize, text: String },
    Insert { new_line: usize, text: String },
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BodyLineDiff {
    pub unified: String,
    pub changed_old_lines: Vec<usize>,
    pub changed_new_lines: Vec<usize>,
}

fn split_lines(body: &str) -> Vec<String> {
    body.split('\n')
        .map(|line| line.strip_suffix('\r').unwrap_or(line).to_string())
        .collect()
}

fn lcs_table(old: &[String], new: &[String]) -> Vec<Vec<u32>> {
    let n = old.len();
    let m = new.len();
    let mut table = vec![vec![0u32; m + 1]; n + 1];
    for i in (0..n).rev() {
        for j in (0..m).rev() {
            table[i][j] = if old[i] == new[j] {
                table[i + 1][j + 1] + 1
            } else {
                table[i + 1][j].max(table[i][j + 1])
            };
        }
    }
    table
}

fn build_ops(old: &[String], new: &[String]) -> Vec<DiffOp> {
    let table = lcs_table(old, new);
    let mut ops = Vec::new();
    let (mut i, mut j) = (0usize, 0usize);
    let n = old.len();
    let m = new.len();
    while i < n && j < m {
        if old[i] == new[j] {
            ops.push(DiffOp::Equal {
                old_line: i + 1,
                new_line: j + 1,
                text: old[i].clone(),
            });
            i += 1;
            j += 1;
        } else if table[i + 1][j] >= table[i][j + 1] {
            ops.push(DiffOp::Delete {
                old_line: i + 1,
                text: old[i].clone(),
            });
            i += 1;
        } else {
            ops.push(DiffOp::Insert {
                new_line: j + 1,
                text: new[j].clone(),
            });
            j += 1;
        }
    }
    while i < n {
        ops.push(DiffOp::Delete {
            old_line: i + 1,
            text: old[i].clone(),
        });
        i += 1;
    }
    while j < m {
        ops.push(DiffOp::Insert {
            new_line: j + 1,
            text: new[j].clone(),
        });
        j += 1;
    }
    ops
}

fn merged_hunk_ranges(ops: &[DiffOp]) -> Vec<(usize, usize)> {
    let change_indices: Vec<usize> = ops
        .iter()
        .enumerate()
        .filter(|(_, op)| !matches!(op, DiffOp::Equal { .. }))
        .map(|(idx, _)| idx)
        .collect();

    let mut ranges: Vec<(usize, usize)> = Vec::new();
    for &idx in &change_indices {
        let lo = idx.saturating_sub(CONTEXT);
        let hi = (idx + CONTEXT).min(ops.len() - 1);
        match ranges.last_mut() {
            Some((_, last_hi)) if lo <= *last_hi + 1 => {
                *last_hi = (*last_hi).max(hi);
            }
            _ => ranges.push((lo, hi)),
        }
    }
    ranges
}

fn render_hunk(ops: &[DiffOp]) -> String {
    let mut old_start = 0usize;
    let mut old_count = 0usize;
    let mut new_start = 0usize;
    let mut new_count = 0usize;
    let mut lines: Vec<String> = Vec::new();

    for op in ops {
        match op {
            DiffOp::Equal { old_line, new_line, text } => {
                if old_start == 0 {
                    old_start = *old_line;
                }
                if new_start == 0 {
                    new_start = *new_line;
                }
                old_count += 1;
                new_count += 1;
                lines.push(format!(" {text}"));
            }
            DiffOp::Delete { old_line, text } => {
                if old_start == 0 {
                    old_start = *old_line;
                }
                old_count += 1;
                lines.push(format!("-{text}"));
            }
            DiffOp::Insert { new_line, text } => {
                if new_start == 0 {
                    new_start = *new_line;
                }
                new_count += 1;
                lines.push(format!("+{text}"));
            }
        }
    }

    let header = format!("@@ -{old_start},{old_count} +{new_start},{new_count} @@");
    let mut hunk = vec![header];
    hunk.extend(lines);
    hunk.join("\n")
}

pub fn diff_body_lines(old_body: &str, new_body: &str) -> BodyLineDiff {
    let old_lines = split_lines(old_body);
    let new_lines = split_lines(new_body);
    let ops = build_ops(&old_lines, &new_lines);

    let changed_old_lines: Vec<usize> = ops
        .iter()
        .filter_map(|op| match op {
            DiffOp::Delete { old_line, .. } => Some(*old_line),
            _ => None,
        })
        .collect();
    let changed_new_lines: Vec<usize> = ops
        .iter()
        .filter_map(|op| match op {
            DiffOp::Insert { new_line, .. } => Some(*new_line),
            _ => None,
        })
        .collect();

    let ranges = merged_hunk_ranges(&ops);
    let hunks: Vec<String> = ranges
        .iter()
        .map(|(lo, hi)| render_hunk(&ops[*lo..=*hi]))
        .collect();
    let unified = hunks.join("\n");

    BodyLineDiff {
        unified,
        changed_old_lines,
        changed_new_lines,
    }
}

pub fn select_intersecting_entries(
    entries: &[AttributionEntry],
    changed_old_lines: &[usize],
) -> Vec<AttributionEntry> {
    let changed: BTreeSet<usize> = changed_old_lines.iter().copied().collect();
    entries
        .iter()
        .filter(|entry| {
            let start = entry.prompt_lines.start as usize;
            let end = entry.prompt_lines.end as usize;
            (start..=end).any(|line| changed.contains(&line))
        })
        .cloned()
        .collect()
}

pub fn incremental_unlock_list(
    owned_files: &[String],
    intersecting_entries: &[AttributionEntry],
    target_rel_to_root: &str,
) -> Vec<String> {
    let mut files: Vec<String> = owned_files.to_vec();
    for entry in intersecting_entries {
        files.push(format!("{target_rel_to_root}/{}", entry.file));
    }
    files.sort();
    files.dedup();
    files
}

#[cfg(test)]
mod tests {
    use super::*;
    use schemas_line_range::LineRange;

    fn entry(prompt_start: u32, prompt_end: u32, file: &str) -> AttributionEntry {
        AttributionEntry {
            prompt_lines: LineRange::new(prompt_start, prompt_end),
            file: file.to_string(),
            lines: LineRange::new(1, 1),
            note: String::new(),
        }
    }

    #[test]
    fn splits_lines_and_strips_cr() {
        let diff = diff_body_lines("a\r\nb\r\n", "a\r\nb\r\n");
        assert!(diff.changed_old_lines.is_empty());
        assert!(diff.changed_new_lines.is_empty());
        assert_eq!(diff.unified, "");
    }

    #[test]
    fn identical_bodies_produce_no_changes() {
        let diff = diff_body_lines("Greet a person by name.", "Greet a person by name.");
        assert_eq!(diff.changed_old_lines, Vec::<usize>::new());
        assert_eq!(diff.changed_new_lines, Vec::<usize>::new());
        assert_eq!(diff.unified, "");
    }

    #[test]
    fn single_line_change_reports_delete_and_insert() {
        let diff = diff_body_lines(
            "Greet a person by name.",
            "Greet a person by name, loudly.",
        );
        assert_eq!(diff.changed_old_lines, vec![1]);
        assert_eq!(diff.changed_new_lines, vec![1]);
        assert!(diff.unified.contains("-Greet a person by name."));
        assert!(diff.unified.contains("+Greet a person by name, loudly."));
        assert!(diff.unified.starts_with("@@ -1,1 +1,1 @@"));
    }

    #[test]
    fn context_lines_are_included_in_hunk() {
        let old = "one\ntwo\nthree\nfour\nfive";
        let new = "one\ntwo\nCHANGED\nfour\nfive";
        let diff = diff_body_lines(old, new);
        assert_eq!(diff.changed_old_lines, vec![3]);
        assert_eq!(diff.changed_new_lines, vec![3]);
        assert_eq!(
            diff.unified,
            "@@ -1,5 +1,5 @@\n one\n two\n-three\n+CHANGED\n four\n five"
        );
    }

    #[test]
    fn distant_changes_split_into_separate_hunks() {
        let old_lines: Vec<String> = (1..=20).map(|n| format!("line{n}")).collect();
        let mut new_lines = old_lines.clone();
        new_lines[0] = "CHANGED1".to_string();
        new_lines[19] = "CHANGED20".to_string();
        let old_body = old_lines.join("\n");
        let new_body = new_lines.join("\n");
        let diff = diff_body_lines(&old_body, &new_body);
        let hunk_count = diff.unified.matches("@@").count() / 2;
        assert_eq!(hunk_count, 2);
    }

    #[test]
    fn adjacent_changes_merge_into_one_hunk() {
        // gap of exactly 6 equal lines between two single-line changes merges.
        let old_lines: Vec<String> = (1..=8).map(|n| format!("line{n}")).collect();
        let mut new_lines = old_lines.clone();
        new_lines[0] = "CHANGED1".to_string();
        new_lines[7] = "CHANGED8".to_string();
        let old_body = old_lines.join("\n");
        let new_body = new_lines.join("\n");
        let diff = diff_body_lines(&old_body, &new_body);
        let hunk_count = diff.unified.matches("@@").count() / 2;
        assert_eq!(hunk_count, 1);
    }

    #[test]
    fn prefers_deletion_on_free_choice() {
        // "a" -> "a" then old has extra "x" vs new has extra "y": tie means delete first.
        let diff = diff_body_lines("a\nx", "a\ny");
        assert_eq!(diff.changed_old_lines, vec![2]);
        assert_eq!(diff.changed_new_lines, vec![2]);
    }

    #[test]
    fn select_intersecting_entries_keeps_only_overlapping_ranges() {
        let entries = vec![
            entry(1, 2, "a.rs"),
            entry(3, 3, "b.rs"),
            entry(5, 6, "c.rs"),
        ];
        let selected = select_intersecting_entries(&entries, &[3, 7]);
        assert_eq!(selected.len(), 1);
        assert_eq!(selected[0].file, "b.rs");
    }

    #[test]
    fn select_intersecting_entries_preserves_order() {
        let entries = vec![entry(5, 5, "z.rs"), entry(1, 1, "a.rs")];
        let selected = select_intersecting_entries(&entries, &[1, 5]);
        assert_eq!(selected.len(), 2);
        assert_eq!(selected[0].file, "z.rs");
        assert_eq!(selected[1].file, "a.rs");
    }

    #[test]
    fn unlock_list_merges_owned_and_intersecting_sorted_deduped() {
        let owned = vec!["b.rs".to_string(), "a.rs".to_string()];
        let entries = vec![entry(1, 1, "a.rs"), entry(2, 2, "c.rs")];
        let unlock = incremental_unlock_list(&owned, &entries, "target/rust");
        assert_eq!(
            unlock,
            vec![
                "a.rs".to_string(),
                "b.rs".to_string(),
                "target/rust/a.rs".to_string(),
                "target/rust/c.rs".to_string(),
            ]
        );
    }

    #[test]
    fn unlock_list_is_empty_when_no_input() {
        let unlock = incremental_unlock_list(&[], &[], "target/rust");
        assert!(unlock.is_empty());
    }
}
