// GENERATED BY NAPL from yaml.napl — edit the prompt, not this file

use schemas_attribution::Attribution;
use schemas_ir::Ir;
use schemas_line_range::LineRange;
use schemas_ml::{Ml, MlKind};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq)]
pub enum Yaml {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Str(String),
    Seq(Vec<Yaml>),
    Map(Vec<(String, Yaml)>),
}

const PLAIN_LEADING_INDICATORS: &[char] =
    &[',', '[', ']', '{', '}', '#', '&', '*', '!', '|', '>', '\'', '"', '%', '@', '`'];

fn is_control_char(c: char) -> bool {
    (c != '\n' && (c as u32) < 0x20) || c == '\u{7f}'
}

fn strip_single_sign(s: &str) -> &str {
    s.strip_prefix('+').or_else(|| s.strip_prefix('-')).unwrap_or(s)
}

fn is_core_integer(s: &str) -> bool {
    let body = strip_single_sign(s);
    if let Some(rest) = body.strip_prefix("0x") {
        return !rest.is_empty() && rest.chars().all(|c| c.is_ascii_hexdigit());
    }
    if let Some(rest) = body.strip_prefix("0o") {
        return !rest.is_empty() && rest.chars().all(|c| ('0'..='7').contains(&c));
    }
    !body.is_empty() && body.chars().all(|c| c.is_ascii_digit())
}

fn is_core_float(s: &str) -> bool {
    let body = strip_single_sign(s);
    if body == ".inf" || body == ".Inf" || body == ".INF" {
        return true;
    }
    if s == ".nan" || s == ".NaN" || s == ".NAN" {
        return true;
    }
    let mut parts = body.splitn(2, |c| c == 'e' || c == 'E');
    let mantissa = parts.next().unwrap_or("");
    let exponent = parts.next();

    if mantissa.matches('.').count() != 1 {
        return false;
    }
    let mut mantissa_parts = mantissa.splitn(2, '.');
    let int_part = mantissa_parts.next().unwrap_or("");
    let frac_part = mantissa_parts.next().unwrap_or("");
    if !int_part.chars().all(|c| c.is_ascii_digit()) || !frac_part.chars().all(|c| c.is_ascii_digit()) {
        return false;
    }
    if int_part.is_empty() && frac_part.is_empty() {
        return false;
    }

    if let Some(exp) = exponent {
        let exp_body = strip_single_sign(exp);
        if exp_body.is_empty() || !exp_body.chars().all(|c| c.is_ascii_digit()) {
            return false;
        }
    }

    true
}

fn resolves_as_non_string(s: &str) -> bool {
    matches!(
        s,
        "null" | "Null" | "NULL" | "~" | "true" | "True" | "TRUE" | "false" | "False" | "FALSE"
    ) || is_core_integer(s)
        || is_core_float(s)
}

fn is_plain_representable(s: &str) -> bool {
    let first = s.chars().next().unwrap();
    let last = s.chars().last().unwrap();
    if first.is_whitespace() || last.is_whitespace() {
        return false;
    }
    if s.chars().any(|c| c == '\n' || is_control_char(c)) {
        return false;
    }
    if PLAIN_LEADING_INDICATORS.contains(&first) {
        return false;
    }
    if first == '-' || first == '?' || first == ':' {
        match s.chars().nth(1) {
            None => return false,
            Some(c2) if c2 == ' ' => return false,
            _ => {}
        }
    }
    if s.contains(": ") || s.ends_with(':') || s.contains(" #") {
        return false;
    }
    if resolves_as_non_string(s) {
        return false;
    }
    true
}

fn render_string_scalar(s: &str) -> String {
    if s.is_empty() {
        return "\"\"".to_string();
    }
    if is_plain_representable(s) {
        return s.to_string();
    }
    if s.contains('"') && !s.contains('\'') {
        return format!("'{}'", s.replace('\'', "''"));
    }
    let mut out = String::from("\"");
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

fn render_scalar(node: &Yaml) -> String {
    match node {
        Yaml::Null => "null".to_string(),
        Yaml::Bool(b) => b.to_string(),
        Yaml::Int(i) => i.to_string(),
        Yaml::Float(f) => f.to_string(),
        Yaml::Str(s) => render_string_scalar(s),
        Yaml::Seq(_) | Yaml::Map(_) => unreachable!("render_scalar called on a container"),
    }
}

fn inline_scalar(node: &Yaml) -> String {
    match node {
        Yaml::Seq(items) if items.is_empty() => "[]".to_string(),
        Yaml::Map(entries) if entries.is_empty() => "{}".to_string(),
        other => render_scalar(other),
    }
}

fn emit_map(entries: &[(String, Yaml)], indent: usize) -> Vec<String> {
    let ind = " ".repeat(indent);
    let mut lines = Vec::new();
    for (key, value) in entries {
        let key_str = render_string_scalar(key);
        match value {
            Yaml::Seq(items) if !items.is_empty() => {
                lines.push(format!("{ind}{key_str}:"));
                lines.extend(emit_seq(items, indent + 2));
            }
            Yaml::Map(inner) if !inner.is_empty() => {
                lines.push(format!("{ind}{key_str}:"));
                lines.extend(emit_map(inner, indent + 2));
            }
            other => {
                lines.push(format!("{ind}{key_str}: {}", inline_scalar(other)));
            }
        }
    }
    lines
}

fn emit_seq(items: &[Yaml], indent: usize) -> Vec<String> {
    let ind = " ".repeat(indent);
    let mut lines = Vec::new();
    for item in items {
        match item {
            Yaml::Map(entries) if !entries.is_empty() => {
                let inner = emit_map(entries, indent + 2);
                let mut inner_iter = inner.into_iter();
                let first = inner_iter.next().unwrap();
                let stripped = &first[(indent + 2)..];
                lines.push(format!("{ind}- {stripped}"));
                lines.extend(inner_iter);
            }
            Yaml::Seq(inner) if !inner.is_empty() => {
                lines.push(format!("{ind}-"));
                lines.extend(emit_seq(inner, indent + 2));
            }
            other => {
                lines.push(format!("{ind}- {}", inline_scalar(other)));
            }
        }
    }
    lines
}

pub fn to_yaml_document(node: &Yaml) -> String {
    let lines = match node {
        Yaml::Map(entries) if !entries.is_empty() => emit_map(entries, 0),
        Yaml::Map(_) => vec!["{}".to_string()],
        Yaml::Seq(items) if !items.is_empty() => emit_seq(items, 0),
        Yaml::Seq(_) => vec!["[]".to_string()],
        other => vec![render_scalar(other)],
    };
    let mut doc = lines.join("\n");
    doc.push('\n');
    doc
}

pub fn line_range(range: LineRange) -> Yaml {
    Yaml::Seq(vec![Yaml::Int(range.start as i64), Yaml::Int(range.end as i64)])
}

fn ml_kind_str(kind: MlKind) -> &'static str {
    match kind {
        MlKind::Ambiguity => "ambiguity",
        MlKind::Assumption => "assumption",
        MlKind::Note => "note",
        MlKind::NoOp => "no-op",
    }
}

pub fn attribution_to_yaml(attribution: &Attribution) -> String {
    let entries = attribution
        .entries
        .iter()
        .map(|entry| {
            Yaml::Map(vec![
                ("promptLines".to_string(), line_range(entry.prompt_lines)),
                ("file".to_string(), Yaml::Str(entry.file.clone())),
                ("lines".to_string(), line_range(entry.lines)),
                ("note".to_string(), Yaml::Str(entry.note.clone())),
            ])
        })
        .collect();
    let doc = Yaml::Map(vec![
        ("module".to_string(), Yaml::Str(attribution.module.clone())),
        ("target".to_string(), Yaml::Str(attribution.target.clone())),
        ("entries".to_string(), Yaml::Seq(entries)),
    ]);
    to_yaml_document(&doc)
}

pub fn ml_to_yaml(ml: &Ml) -> String {
    let entries = ml
        .entries
        .iter()
        .map(|entry| {
            let mut fields = vec![
                ("promptLines".to_string(), line_range(entry.prompt_lines)),
                ("kind".to_string(), Yaml::Str(ml_kind_str(entry.kind).to_string())),
                ("message".to_string(), Yaml::Str(entry.message.clone())),
                ("reasoning".to_string(), Yaml::Str(entry.reasoning.clone())),
            ];
            if let Some(suggestion) = &entry.suggestion {
                fields.push(("suggestion".to_string(), Yaml::Str(suggestion.clone())));
            }
            Yaml::Map(fields)
        })
        .collect();
    let doc = Yaml::Map(vec![
        ("module".to_string(), Yaml::Str(ml.module.clone())),
        ("target".to_string(), Yaml::Str(ml.target.clone())),
        ("entries".to_string(), Yaml::Seq(entries)),
    ]);
    to_yaml_document(&doc)
}

pub fn json_to_yaml(value: &Value) -> Yaml {
    match value {
        Value::Null => Yaml::Null,
        Value::Bool(b) => Yaml::Bool(*b),
        Value::Number(n) => match n.as_i64() {
            Some(i) => Yaml::Int(i),
            None => Yaml::Float(n.as_f64().unwrap_or(0.0)),
        },
        Value::String(s) => Yaml::Str(s.clone()),
        Value::Array(items) => Yaml::Seq(items.iter().map(json_to_yaml).collect()),
        Value::Object(map) => Yaml::Map(map.iter().map(|(k, v)| (k.clone(), json_to_yaml(v))).collect()),
    }
}

pub fn ir_to_yaml(ir: &Ir) -> String {
    let deps = ir.deps.iter().map(|d| Yaml::Str(d.clone())).collect();
    let types = ir
        .types
        .iter()
        .map(|t| {
            Yaml::Map(vec![
                ("name".to_string(), Yaml::Str(t.name.clone())),
                ("description".to_string(), Yaml::Str(t.description.clone())),
            ])
        })
        .collect();
    let functions = ir
        .functions
        .iter()
        .map(|f| {
            Yaml::Map(vec![
                ("name".to_string(), Yaml::Str(f.name.clone())),
                ("signature".to_string(), Yaml::Str(f.signature.clone())),
                ("behavior".to_string(), Yaml::Str(f.behavior.clone())),
            ])
        })
        .collect();
    let tests = ir
        .tests
        .iter()
        .map(|t| {
            Yaml::Map(vec![
                ("name".to_string(), Yaml::Str(t.name.clone())),
                ("given".to_string(), json_to_yaml(&t.given)),
                ("expect".to_string(), json_to_yaml(&t.expect)),
            ])
        })
        .collect();
    let doc = Yaml::Map(vec![
        ("module".to_string(), Yaml::Str(ir.module.clone())),
        ("deps".to_string(), Yaml::Seq(deps)),
        ("types".to_string(), Yaml::Seq(types)),
        ("functions".to_string(), Yaml::Seq(functions)),
        ("tests".to_string(), Yaml::Seq(tests)),
    ]);
    to_yaml_document(&doc)
}

#[cfg(test)]
mod tests {
    use super::*;
    use schemas_attribution::validate_attribution;
    use schemas_ir::validate_ir;
    use schemas_ml::validate_ml;
    use serde_json::json;

    #[test]
    fn empty_string_is_double_quoted_empty() {
        assert_eq!(render_string_scalar(""), "\"\"");
    }

    #[test]
    fn plain_strings_stay_plain() {
        for s in [
            "yes",
            "on",
            "Off",
            "no",
            "it's fine",
            "colon:nospace",
            "Returns the string Hello, name!",
        ] {
            assert_eq!(render_string_scalar(s), s, "expected {s} to stay plain");
        }
    }

    #[test]
    fn non_plain_strings_are_quoted() {
        assert_eq!(render_string_scalar("true"), "\"true\"");
        assert_eq!(render_string_scalar("123"), "\"123\"");
        assert_eq!(render_string_scalar("null"), "\"null\"");
        assert_eq!(render_string_scalar("~"), "\"~\"");
        assert_eq!(render_string_scalar("1.5"), "\"1.5\"");
        assert_eq!(render_string_scalar("0x10"), "\"0x10\"");
        assert_eq!(render_string_scalar(".inf"), "\".inf\"");
        assert_eq!(
            render_string_scalar("greet(name: string): string"),
            "\"greet(name: string): string\""
        );
        assert_eq!(render_string_scalar("a: b"), "\"a: b\"");
        assert_eq!(render_string_scalar("has # hash"), "\"has # hash\"");
        assert_eq!(render_string_scalar("- dashlead"), "\"- dashlead\"");
        assert_eq!(render_string_scalar("end colon:"), "\"end colon:\"");
        assert_eq!(render_string_scalar("#leadinghash"), "\"#leadinghash\"");
        assert_eq!(render_string_scalar(" leadingspace"), "\" leadingspace\"");
        assert_eq!(render_string_scalar("trailingspace "), "\"trailingspace \"");
        assert_eq!(
            render_string_scalar("only ' apostrophe: with colon"),
            "\"only ' apostrophe: with colon\""
        );
    }

    #[test]
    fn double_quote_without_apostrophe_becomes_single_quoted() {
        assert_eq!(
            render_string_scalar("\"loudly\" is vague"),
            "'\"loudly\" is vague'"
        );
    }

    #[test]
    fn double_quoted_escapes_special_characters() {
        // the embedded newline forces quoting (plain forbids newlines); every other
        // special character in the string must be escaped once quoting kicks in.
        assert_eq!(
            render_string_scalar("a\nb\tc\rd\\e"),
            "\"a\\nb\\tc\\rd\\\\e\""
        );
        // leading quote forces quoting; presence of an apostrophe rules out the
        // single-quote branch, so this falls to double-quoted with `"` escaped.
        assert_eq!(
            render_string_scalar("\"hi\" it's ok"),
            "\"\\\"hi\\\" it's ok\""
        );
    }

    #[test]
    fn non_string_scalars_render_directly() {
        assert_eq!(render_scalar(&Yaml::Null), "null");
        assert_eq!(render_scalar(&Yaml::Bool(true)), "true");
        assert_eq!(render_scalar(&Yaml::Bool(false)), "false");
        assert_eq!(render_scalar(&Yaml::Int(-42)), "-42");
        assert_eq!(render_scalar(&Yaml::Float(1.5)), "1.5");
    }

    #[test]
    fn document_empty_map_and_seq_are_inline() {
        assert_eq!(to_yaml_document(&Yaml::Map(vec![])), "{}\n");
        assert_eq!(to_yaml_document(&Yaml::Seq(vec![])), "[]\n");
    }

    #[test]
    fn document_scalar_root() {
        assert_eq!(to_yaml_document(&Yaml::Str("hello".to_string())), "hello\n");
        assert_eq!(to_yaml_document(&Yaml::Int(7)), "7\n");
    }

    #[test]
    fn document_flat_map() {
        let doc = Yaml::Map(vec![
            ("a".to_string(), Yaml::Str("x".to_string())),
            ("b".to_string(), Yaml::Int(3)),
        ]);
        assert_eq!(to_yaml_document(&doc), "a: x\nb: 3\n");
    }

    #[test]
    fn document_nested_seq_of_maps() {
        let doc = Yaml::Map(vec![(
            "items".to_string(),
            Yaml::Seq(vec![
                Yaml::Map(vec![("k".to_string(), Yaml::Int(1))]),
                Yaml::Map(vec![("k".to_string(), Yaml::Int(2))]),
            ]),
        )]);
        assert_eq!(to_yaml_document(&doc), "items:\n  - k: 1\n  - k: 2\n");
    }

    #[test]
    fn document_seq_of_seq() {
        let doc = Yaml::Seq(vec![Yaml::Seq(vec![Yaml::Int(1), Yaml::Int(2)])]);
        assert_eq!(to_yaml_document(&doc), "-\n  - 1\n  - 2\n");
    }

    #[test]
    fn attribution_matches_expected_bytes() {
        let attribution = validate_attribution(json!({
            "module": "greeting",
            "target": "typescript",
            "entries": [
                {
                    "promptLines": [1, 1],
                    "file": "greet.ts",
                    "lines": [1, 1],
                    "note": "builds the greeting string"
                }
            ]
        }))
        .unwrap();

        let expected = concat!(
            "module: greeting\n",
            "target: typescript\n",
            "entries:\n",
            "  - promptLines:\n",
            "      - 1\n",
            "      - 1\n",
            "    file: greet.ts\n",
            "    lines:\n",
            "      - 1\n",
            "      - 1\n",
            "    note: builds the greeting string\n",
        );

        assert_eq!(attribution_to_yaml(&attribution), expected);
    }

    #[test]
    fn ml_empty_entries_render_inline() {
        let ml = validate_ml(json!({"module": "m", "target": "t"})).unwrap();
        assert_eq!(ml_to_yaml(&ml), "module: m\ntarget: t\nentries: []\n");
    }

    #[test]
    fn ml_entry_kinds_and_optional_suggestion() {
        let ml = validate_ml(json!({
            "module": "m",
            "target": "t",
            "entries": [
                {"promptLines": [1, 2], "kind": "no-op", "message": "msg", "reasoning": "why", "suggestion": "do this"},
                {"promptLines": 5, "kind": "note", "message": "m2"}
            ]
        }))
        .unwrap();

        let expected = concat!(
            "module: m\n",
            "target: t\n",
            "entries:\n",
            "  - promptLines:\n",
            "      - 1\n",
            "      - 2\n",
            "    kind: no-op\n",
            "    message: msg\n",
            "    reasoning: why\n",
            "    suggestion: do this\n",
            "  - promptLines:\n",
            "      - 5\n",
            "      - 5\n",
            "    kind: note\n",
            "    message: m2\n",
            "    reasoning: \"\"\n",
        );

        assert_eq!(ml_to_yaml(&ml), expected);
    }

    #[test]
    fn ir_empty_sequences_render_inline() {
        let ir = validate_ir(json!({"module": "m"})).unwrap();
        assert_eq!(
            ir_to_yaml(&ir),
            "module: m\ndeps: []\ntypes: []\nfunctions: []\ntests: []\n"
        );
    }

    #[test]
    fn ir_with_content_and_json_test_values() {
        let ir = validate_ir(json!({
            "module": "greeting",
            "deps": ["a", "b"],
            "types": [{"name": "T", "description": "desc"}],
            "functions": [{"name": "f", "signature": "f(): string", "behavior": "returns"}],
            "tests": [{"name": "t1", "given": {"x": 1, "y": [1, 2]}, "expect": "ok"}]
        }))
        .unwrap();

        let expected = concat!(
            "module: greeting\n",
            "deps:\n",
            "  - a\n",
            "  - b\n",
            "types:\n",
            "  - name: T\n",
            "    description: desc\n",
            "functions:\n",
            "  - name: f\n",
            "    signature: \"f(): string\"\n",
            "    behavior: returns\n",
            "tests:\n",
            "  - name: t1\n",
            "    given:\n",
            "      x: 1\n",
            "      y:\n",
            "        - 1\n",
            "        - 2\n",
            "    expect: ok\n",
        );

        assert_eq!(ir_to_yaml(&ir), expected);
    }

    #[test]
    fn json_to_yaml_converts_all_value_kinds() {
        assert_eq!(json_to_yaml(&json!(null)), Yaml::Null);
        assert_eq!(json_to_yaml(&json!(true)), Yaml::Bool(true));
        assert_eq!(json_to_yaml(&json!(5)), Yaml::Int(5));
        assert_eq!(json_to_yaml(&json!(1.5)), Yaml::Float(1.5));
        assert_eq!(json_to_yaml(&json!("s")), Yaml::Str("s".to_string()));
        assert_eq!(
            json_to_yaml(&json!([1, "a"])),
            Yaml::Seq(vec![Yaml::Int(1), Yaml::Str("a".to_string())])
        );
        assert_eq!(
            json_to_yaml(&json!({"k": 1})),
            Yaml::Map(vec![("k".to_string(), Yaml::Int(1))])
        );
    }

    #[test]
    fn line_range_builds_two_int_seq() {
        assert_eq!(
            line_range(LineRange::new(3, 9)),
            Yaml::Seq(vec![Yaml::Int(3), Yaml::Int(9)])
        );
    }
}
