// GENERATED BY NAPL from state_io.napl — edit the prompt, not this file
//! On-disk state: the map, the journal, and the lock.
//!
//! The CLI's persistent-state seam. The pure parsing, serialization, and
//! validation live in the generated schema crates; this module adds the
//! filesystem I/O around them. Every function touches the real filesystem, so
//! this is an I/O shell — it declares no given/expect corpus and is pinned by
//! filesystem round-trip tests.
//!
//! Every error string is the bare underlying message: a parse failure is the
//! schema parser's error rendered as a string, an I/O failure is the I/O
//! error's display, a serialization failure is the serializer's error display.
//! The only hard-coded message is the missing-lock message.

use std::path::Path;

use extensions::default_prompt_aliases;
use schemas_journal::JournalEntry;
use schemas_lock::{default_agent_config, parse_lock, resolve_prompt_aliases, Backend, HlLock, DEFAULT_MODEL};
use schemas_map::{empty_map, map_to_json, parse_map, NaplMap};

/// The message returned when the lock file is absent.
const MISSING_LOCK: &str = "missing .napl/lock.json — run 'napl init' first";

/// Read and parse the module map at `map_path`, defaulting to the empty map
/// when the file is absent.
pub fn read_map(map_path: &Path) -> Result<NaplMap, String> {
    match fsutil_io::read_opt(map_path).map_err(|e| e.to_string())? {
        Some(raw) => parse_map(&raw),
        None => Ok(empty_map()),
    }
}

/// Serialize `map` and write it to `map_path`, creating parent directories.
pub fn write_map(map_path: &Path, map: &NaplMap) -> Result<(), String> {
    fsutil_io::write(map_path, &map_to_json(map)).map_err(|e| e.to_string())
}

/// Read the journal at `journal_path`, returning its valid entries and the
/// warnings for skipped lines. An absent journal reads as empty.
pub fn read_journal(journal_path: &Path) -> Result<(Vec<JournalEntry>, Vec<String>), String> {
    match fsutil_io::read_opt(journal_path).map_err(|e| e.to_string())? {
        Some(raw) => Ok(schemas_journal::read_journal_str(&raw)),
        None => Ok((Vec::new(), Vec::new())),
    }
}

/// Append one compact JSON line for `entry` to the journal at `journal_path`.
pub fn append_journal_entry(journal_path: &Path, entry: &JournalEntry) -> Result<(), String> {
    fsutil_io::mkdir_parent(journal_path).map_err(|e| e.to_string())?;
    let line = serde_json::to_string(entry).map_err(|e| e.to_string())?;
    let existing = fsutil_io::read_opt(journal_path)
        .map_err(|e| e.to_string())?
        .unwrap_or_default();
    let content = format!("{existing}{line}\n");
    fsutil_io::write(journal_path, &content).map_err(|e| e.to_string())
}

/// Read, parse, and validate the lock at `lock_path`.
pub fn read_lock(lock_path: &Path) -> Result<HlLock, String> {
    match fsutil_io::read_opt(lock_path).map_err(|e| e.to_string())? {
        Some(raw) => parse_lock(&raw).map_err(|e| e.to_string()),
        None => Err(MISSING_LOCK.to_string()),
    }
}

/// Write `lock` as pretty JSON with a trailing newline to `lock_path`.
pub fn write_lock(lock_path: &Path, lock: &HlLock) -> Result<(), String> {
    let mut json = serde_json::to_string_pretty(lock).map_err(|e| e.to_string())?;
    json.push('\n');
    fsutil_io::write(lock_path, &json).map_err(|e| e.to_string())
}

/// The default lock document written by `napl init`.
pub fn default_lock() -> HlLock {
    HlLock {
        model: DEFAULT_MODEL.to_string(),
        backend: Backend::ClaudeCli,
        prompt_aliases: None,
        agent: Some(default_agent_config()),
    }
}

/// Resolve the effective prompt-file aliases, falling back to the defaults for
/// an absent, unreadable, or invalid lock.
pub fn load_prompt_aliases(lock_path: &Path) -> Vec<String> {
    match fsutil_io::read_opt(lock_path) {
        Ok(Some(raw)) => match parse_lock(&raw) {
            Ok(lock) => resolve_prompt_aliases(&lock),
            Err(_) => default_prompt_aliases(),
        },
        _ => default_prompt_aliases(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::PathBuf;
    use std::process;

    struct TmpDir {
        path: PathBuf,
    }

    impl TmpDir {
        fn new(tag: &str) -> TmpDir {
            let mut path = std::env::temp_dir();
            // pid + a per-tag suffix keeps concurrent tests from colliding.
            path.push(format!("state_io-{}-{}", process::id(), tag));
            fs::create_dir_all(&path).unwrap();
            TmpDir { path }
        }

        fn join(&self, name: &str) -> PathBuf {
            self.path.join(name)
        }
    }

    impl Drop for TmpDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.path);
        }
    }

    #[test]
    fn read_map_defaults_to_the_empty_map() {
        let dir = TmpDir::new("read-map-absent");
        let map = read_map(&dir.join("missing/map.json")).unwrap();
        assert_eq!(map_to_json(&map), map_to_json(&empty_map()));
    }

    #[test]
    fn read_lock_reports_the_missing_lock_message() {
        let dir = TmpDir::new("read-lock-absent");
        let err = read_lock(&dir.join("lock.json")).unwrap_err();
        assert_eq!(err, "missing .napl/lock.json — run 'napl init' first");
    }

    #[test]
    fn write_lock_round_trips_the_default_lock() {
        let dir = TmpDir::new("write-lock");
        let path = dir.join("nested/lock.json");
        write_lock(&path, &default_lock()).unwrap();
        let raw = fs::read_to_string(&path).unwrap();
        assert!(raw.ends_with('\n'));
        assert_eq!(read_lock(&path).unwrap(), default_lock());
    }

    #[test]
    fn write_map_round_trips_the_empty_map() {
        let dir = TmpDir::new("write-map");
        let path = dir.join("nested/map.json");
        write_map(&path, &empty_map()).unwrap();
        let map = read_map(&path).unwrap();
        assert_eq!(map_to_json(&map), map_to_json(&empty_map()));
    }

    #[test]
    fn read_map_propagates_a_parse_error() {
        let dir = TmpDir::new("read-map-bad");
        let path = dir.join("map.json");
        fs::write(&path, "{ not json").unwrap();
        assert!(read_map(&path).is_err());
    }

    #[test]
    fn read_journal_defaults_to_empty() {
        let dir = TmpDir::new("read-journal-absent");
        let (entries, warnings) = read_journal(&dir.join("journal.jsonl")).unwrap();
        assert!(entries.is_empty());
        assert!(warnings.is_empty());
    }

    #[test]
    fn append_journal_entry_appends_one_line_each_time() {
        let dir = TmpDir::new("append-journal");
        let path = dir.join("nested/journal.jsonl");
        let entry = JournalEntry {
            gen: 1,
            timestamp: "1970-01-01T00:00:00Z".to_string(),
            module: "state_io".to_string(),
            target: "rust".to_string(),
            prompt_hash: "abc".to_string(),
            prompt_diff: String::new(),
            mode: schemas_journal::JournalMode::Full,
            files: Vec::new(),
        };
        append_journal_entry(&path, &entry).unwrap();
        let mut second = entry.clone();
        second.gen = 2;
        append_journal_entry(&path, &second).unwrap();

        let raw = fs::read_to_string(&path).unwrap();
        assert_eq!(raw.lines().count(), 2);
        assert!(!raw.lines().next().unwrap().contains('\n'));

        let (entries, warnings) = read_journal(&path).unwrap();
        assert_eq!(entries, vec![entry, second]);
        assert!(warnings.is_empty());
    }

    #[test]
    fn load_prompt_aliases_falls_back_and_resolves() {
        let dir = TmpDir::new("aliases");
        let missing = dir.join("lock.json");
        assert_eq!(load_prompt_aliases(&missing), default_prompt_aliases());

        let broken = dir.join("broken.json");
        fs::write(&broken, "{ not json").unwrap();
        assert_eq!(load_prompt_aliases(&broken), default_prompt_aliases());

        let custom = dir.join("custom.json");
        let mut lock = default_lock();
        lock.prompt_aliases = Some(vec![".🧑".to_string()]);
        write_lock(&custom, &lock).unwrap();
        assert_eq!(load_prompt_aliases(&custom), resolve_prompt_aliases(&lock));
    }
}
